sudo: required
language: node_js
node_js:
  - "14.1.0"

dist: trusty

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

services:
  - mongodb
  - redis
env:
  - NODE_ENV=ci PORT=3000

cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
install:
  - yarn install
  - yarn run build
script:
  - nohup yarn start &
  - sleep 3
  - yarn test
