language: node_js
node_js:
 - '14.1.0'
 - npm install yarn@1.22.4
dist: trusty

before_install:
 - nvm install yarn@1.22.4

services:
 - mongodb
 - redis
env:
 - NODE_ENV=ci PORT=3000

cache:
 yarn: true
 directories:
  - node_modules
  - client/node_modules
install:
 - yarn install
 - yarn run build
script:
 - nohup yarn start &
 - sleep 3
 - yarn test
